version = 0.1
[default.deploy.parameters]
stack_name = "global-table-demo"
resolve_s3 = true
s3_prefix = "global-table-demo"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
