AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: chapter5-api-python

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 512
    Timeout: 25
    Environment:
      Variables:
        LOCATIONS_TABLE: !Ref LocationsTable
  Api:
    OpenApiVersion: '3.0.1'

Resources:
  ProductionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "production"
      Description: "Production API"

  TestingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "testing"
      Description: "Production API"

  LocationsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: locationName
        Type: String

  WeatherEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: weather_event_lambda.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LocationsTable
      Events:
        ProductionEvents:
          Type: Api
          Properties:
            RestApiId: !Ref ProductionApi
            Path: /events
            Method: POST
        TestingEvents:
          Type: Api
          Properties:
            RestApiId: !Ref TestingApi
            Path: /events
            Method: POST

  WeatherQueryLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: weather_query_lambda.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LocationsTable
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /locations
            Method: GET

Outputs:
  DynamoDBTable:
    Description: "DynamoDB Table Name"
    Value: !Ref LocationsTable

  ProductionEndpoint:
    Description: "Production API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/production"

  TestingEndpoint:
    Description: "Production API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/testing"
